name: Clone to AWS S3

on:
  push:
    branches:
      - version1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Sync to S3
        run: |
          aws s3 sync . s3://git-webforpublic/version1/ --exclude ".git/*"

      - name: Create zip file
        run: |
          git archive -o version1.zip HEAD

      - name: Sync to S3
        run: |
          aws s3 cp version1.zip s3://git-webforpublic/

